### ISSUE TITLE
[BUG] UTF8/Unicode Not working correctly

### ISSUE THREAD

**Issue by bReChThOu** [turbosmurfen/spoton#8]
**Describe the bug**
Unicode characters are displayed as _???_

**To Reproduce**
Open Spotify
Play a random track from _Rauf & Faik_
Example (web url): https://open.spotify.com/track/28ANlEDKpDwmpESwlbNMAV?si=aa2d010ef77b47ed

Run the plugin: **//echo -a $dll(spoton.dll,song,)**
Output: **Rauf & Faik - ??? ????? ???????**

**Expected behavior**
Rauf & Faik  - что такое любовь?

**Screenshots**
![image](https://user-images.githubusercontent.com/6891027/153201523-2a7ef65e-3e66-4dc7-b851-aab69066d590.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10
 - Edition: Enterprise
 - Architecture: 64bit
 - mIRC: 7.61

**Comment by turbosmurfen** [comment]
Thanks for the report. I didn't reply instantly because I focused on implementing this. So now after some pauses and programming I got a result. I wonder if you have time can you please test out [Alpha 0.0.1](https://github.com/turbosmurfen/spoton/releases/tag/0.0.1), It would be nice if you also could write back here if this is the result you was looking for. Remember that Alpha is not 100% finished and also only song inside this DLL-File.

**Comment by bReChThOu** [comment]
Hey! Thank you for the quick reply. I downloaded and tested the Alpha file and it works:

![image](https://user-images.githubusercontent.com/6891027/153293906-e78f1a44-4713-4a2a-a7aa-fdd86448d09a.png)

**Comment by turbosmurfen** [comment]
Nice that it works. Now I can add this to release channel. If you wait a bit I will update the whole code.

**Comment by bReChThOu** [comment]
Sure. I'll use the alpha.dll untillthen. I will close the bug.
